#加密配置
jasypt:
  encryptor:
    password: lengleng

server:
  tomcat:
    max-threads: 500 # Maximum amount of worker threads.
    min-spare-threads: 50 # Minimum amount of worker threads

spring:
  cloud: 
    stream: 
      default-binder: kafka
      kafka: 
        binder:
          zk-nodes: 49.4.12.198:2181
          brokers: 49.4.12.198:9092
  redis:
    remote: false        #cachecloud 获取
    host: 49.4.12.13
    port: 6666
    password: moshushi123
  http:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

redis:
  cache:
    expiration: 3601

ribbon:
  eager-load:
    enabled: true
    clients: unis-auth,unis-upms-service,unis-project-service,unis-expert-service,unis-search-service
  Httpclient:
    enabled: false
  OkHttp:
    enabled: true
  ReadTimeout: 30000
  ConnectTimeout: 30000

feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  client:
    config:
      feignName:
        connectTimeout: 30000
        readTimeout: 30000
  compression:
    request:
      enabled: true
    response:
      enabled: true

hystrix:
  threadpool:
    default:
      coreSize: 500
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 800
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

#监控短点配置
management:
  security:
    enabled: false
endpoints:
  actuator:
    enabled: true
  shutdown:
    enabled: false
