spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: moshushi123
    url: jdbc:mysql://192.168.1.105:3306/unis?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    request-context-attribute: rc
    suffix: .ftl
    template-loader-path: classpath:/templates/
