server:
  port: 4060
spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 49.4.12.66:9300
    solr:
      host: http://192.168.1.150:8983/solr
    mongodb:
      uri: mongodb://192.168.1.8:30001
      database: gssj
    elasticjob:
      zookeeper:
        server-lists: 49.4.12.198:2181
        namespace: unis-daemon
#   datasource:
#     type: com.zaxxer.hikari.HikariDataSource
#     driver-class-name: com.mysql.jdbc.Driver
#     username: root
#     password: moshushi123
#     url: jdbc:mysql://49.4.12.66:3306/unis?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
# mybatis-plus:
#   mapper-locations: classpath:/mapper/*Mapper.xml
#   typeAliasesPackage: com.codecraft.unis.*.model.entity
#   global-config:
#     #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#     id-type: 0
#     #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#     field-strategy: 1
#     #驼峰下划线转换
#     db-column-underline: true
#     #刷新mapper 调试神器
#     refresh-mapper: true
#     #数据库大写下划线转换
#     #capital-mode: true
#   configuration:
#     map-underscore-to-camel-case: true
#     cache-enabled: true
