server:
  port: 5001

spring:
  # zipkin:
  #     base-url: http://localhost:5002
  # sleuth:
  #   enabled: true
  #   sampler:
  #     percentage: 1
  boot:
    admin:
      turbine:
        location: unis-monitor
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,turbine.stream

turbine:
    app-config: unis-gateway #收集监控信息的服务名
    combine-host-port: true
    cluster-name-expression: new String('default') #集群名称

notifier:
  mobile:
    enabled: true
    mobiles:
      - 18810284375
  dingTalk:
    enabled: true
