server:
  port: 3000
  
# datasoure默认使用JDBC
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: moshushi123
    url: jdbc:mysql://49.4.12.66:3306/unis-test?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
      
unis:
  auth:
    clientId: unis123
    clientSecret: unis123
    scope: server
  social:
    qq:
      providerId: qq
      clientId: ENC(jYTHlVSN8p2C3KrLz40H7JJYZcQs3SAK)
      clientSecret: ENC(DmTyBXeNFG7Z6pooPCtDUMcI1MYTiO3ldaEOuVWmOTpgDVmyGMsI42hz6OM+0pEE)

urls:
  anon:
    - /authentication/**
    - /**/*.ico
    - /**/*.css
    - /**/*.js
    - /social
    - /signin
    - /signup
    - /info
    - /health
    - /metrics/**
    - /loggers/**
    - /mobile/token
fdfs:
  file-host: http://49.4.12.152:8888/
  tracker-list:
    - 49.4.12.152:22122
bus: 
  test: wwq123
logging:
  config: classpath:logback.xml

